<template>
  <div class="loadingio-spinner-rolling-twa9w6xm7h">
    <div class="ldio-dmrhvk2ple5">
      <div></div>
    </div>
  </div>
</template>

<style type="text/css">
@keyframes ldio-dmrhvk2ple5 {
  0% {
    transform: translate(-50%, -50%) rotate(0deg);
  }
  100% {
    transform: translate(-50%, -50%) rotate(360deg);
  }
}
.ldio-dmrhvk2ple5 div {
  position: absolute;
  width: 50px;
  height: 50px;
  border: 5px solid #85a2b6;
  border-top-color: transparent;
  border-radius: 50%;
}
.ldio-dmrhvk2ple5 div {
  animation: ldio-dmrhvk2ple5 1s linear infinite;
  top: 50px;
  left: 100px;
}
.loadingio-spinner-rolling-twa9w6xm7h {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: rgba(241, 242, 243, 0);
}
.ldio-dmrhvk2ple5 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-dmrhvk2ple5 div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>